# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS_cord_app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS_cord_app
  pod 'SVProgressHUD'

end
